apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: default
servers: 1
agents: 2
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5555"

# TODO: mount /etc/machine-id to all nodes as some tools need it, see https://github.com/grafana/tns/blob/main/create-k3d-cluster
